### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by Cathryn2003** [carlodandan/Custom-Recovery-Builder#20]
![Screenshot_20240211-085824_Chrome](https://github.com/carlodandan/Custom-Recovery-Builder/assets/122968115/2716d0e3-6e0d-48cd-bdd6-a0bb0edb2943)

Zopflipng error

**Comment by carlodandan** [comment]
> ![Screenshot_20240211-085824_Chrome](https://private-user-images.githubusercontent.com/122968115/303896248-2716d0e3-6e0d-48cd-bdd6-a0bb0edb2943.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NDM0NTEsIm5iZiI6MTcwNzY0MzE1MSwicGF0aCI6Ii8xMjI5NjgxMTUvMzAzODk2MjQ4LTI3MTZkMGUzLTZlMGQtNDhjZC1iZGQ2LWEwYmIwZWRiMjk0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMVQwOTE5MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kN2VkMGIxNDc3Nzc0ZTI2OTc1NmQ0NWRhZmJkMDM5YzIxYWEwYWI2YzYyNDNiY2JjODQ5ZmZmYzJlNTE1ODVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HmGevO7oZX6W6mUec4b-40dwHb23WSTgMQXjNgVHOns)
> 
> Zopflipng error

I'll look into it, wait.

**Comment by carlodandan** [comment]
So apparently, zopflipng error only occur in branch 11 and below of pbrp manifest. 12.1 doing fine.


Please update your tree to match with android-12.1 manifest (if theres any changes needed). Branch android-11 is not updated anymore, according to their group.

**Comment by Cathryn2003** [comment]
Ohh okie thanks
